# Generated by Django 4.1.1 on 2023-03-19 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vinstarapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='email',
            new_name='uemail',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='username',
            new_name='uname',
        ),
    ]
