# Generated by Django 4.1.1 on 2023-03-19 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vinstarapp', '0002_rename_email_client_uemail_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='uid',
            new_name='contact',
        ),
    ]
