# Generated by Django 4.1.1 on 2023-03-19 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vinstarapp', '0003_rename_uid_client_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='contact',
        ),
    ]
