# Generated by Django 4.1.1 on 2023-03-20 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vinstarapp', '0004_remove_client_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
    ]
