# Generated by Django 4.1.1 on 2023-03-20 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vinstarapp', '0006_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
